[menu]
  [[menu.header]]
    name = "à propos"
    weight = 1
    url = "/about/"
  [[menu.header]]
    name = "compétences"
    weight = 2
    url = "/skills/"
  [[menu.header]]
    name = "projets"
    weight = 3
    url = "/projets/"
  [[menu.header]]
    name = "articles"
    weight = 4
    url = "/articles/"


[params]
  Name = "Matteo Zinutti"
  HeaderUsername = "Matteoz"
  HeaderHostname = "portfolio"
  About = "Étudiant en M1 DevOps et Cloud, je cultive ma passion pour l'automatisation et les infrastructures cloud. Mon homelab est mon terrain de jeu où je peux pratiquer sans limites les connaissances que j'acquiers de mon côté tel que AWS, Ansible, Docker, Terraform."
  ProfilePicture = "/profilepic.png"
  favicon = "/profilepic.png"
  GithubID = "Toxma"
  LinkedInID = "matteozinutti"
  CvURL = "cv-matteo-zinutti.pdf"
  Email = "matteo.zinutti@gmail.com"



