[menu]
  [[menu.header]]
    name = "À propos"
    weight = 1
    url = "/about/"
  [[menu.header]]
    name = "Compétences"
    weight = 2
    url = "/skills/"
  [[menu.header]]
    name = "Projets"
    weight = 3
    url = "/projets/"
  [[menu.header]]
    name = "Articles"
    weight = 4
    url = "/articles/"


[params]
  Name = "Matteo Zinutti"
  HeaderUsername = "Matteoz"
  HeaderHostname = "portfolio"
  About = "Actuellement en 3ème année de Bachelor Systèmes, Réseaux et Cloud à Sup De Vinci. Je souhaite par le futur poursuivre mes études en Mastère DevOps & Cloud."
  ProfilePicture = "/profilepic.png"
  favicon = "/profilepic.png"
  GithubID = "Toxma"
  LinkedInID = "matteozinutti"
  CvURL = "cv-matteo-zinutti.pdf"
  Email = "matteo.zinutti@gmail.com"



