baseURL = "https://mzinutti.fr/portofolio.io/"
languageCode = 'fr-fr'
title = 'Matteo Zinutti - Portfolio'


[menu]
  [[menu.header]]
    name = "à propos"
    weight = 1
    url = "/about/"
  [[menu.header]]
    name = "compétences"
    weight = 2
    url = "/skills/"
  [[menu.header]]
    name = "projets"
    weight = 3
    url = "/projets/"
  [[menu.header]]
    name = "articles"
    weight = 4
    url = "/blog/"


[params]
  Name = "Matteo Zinutti"
  HeaderUsername = "Matteoz"
  HeaderHostname = "portfolio"
  About = "Actuellement en 3ème année de Bachelor Systèmes, Réseaux et Cloud à Sup De Vinci. Je souhaite par le futur poursuivre mes études en Mastère DevOps & Cloud."
  ProfilePicture = "profilepic.png"
  favicon = "static/profilepic.png"
  GithubID = "Toxma"
  LinkedInID = "matteozinutti"
  CvURL = "cv-matteo-zinutti.pdf"
  Email = "matteo.zinutti@gmail.com"



